# -*- coding: utf-8 -*-
"""Lista 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vA1LNEb-cCR1_6IrXEcFUs-TLGX7ETTS

Nome: Arthur Pereira Vale

 Turma : Quinta N2

 Disciplina : Técnicas de desenvolvimento de algoritmo
"""

print ("Meu primeiro programa!!!")

numero = int(input("Digite um número inteiro: "))

print(numero)

numero = int(input("Digite um número inteiro: "))

print(f"Foi informado o valor:")

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))

print(f"Voce informou os numeros {num1} e {num2}")

numero = float(input("Digite um número real: "))

print(f"Voce informou o numero {numero:.2f}")

celsius = float(input("Digite a temperatura em graus Celsius: "))

fahrenheit = celsius * 1.8 + 32

print(f"A temperatura em Fahrenheit é: {fahrenheit:.2f}")

num_inteiro = int(input("Digite um número inteiro: "))
num_real = float(input("Digite um número real: "))

print(f"Voce informou os numeros {num_inteiro} e {num_real:.2f}")

letra = input("Digite a primeira letra do seu nome: ")

print(f"Voce digitou {letra}")

cor = input("Digite sua cor preferida: ")

print(f"Voce gosta da cor {cor}")

verdura = input("Digite o nome de uma verdura: ")
fruta = input("Digite o nome de uma fruta: ")

print(f"Voce gosta de {verdura} e {fruta}")

numero = float(input("Digite um número real: "))

dobro = numero * 2

print(f"Numero -> {numero}")
print(f"Dobro deste numero -> {dobro}")

numero = float(input("Digite um número real: "))

quadrado = numero ** 2
cubo = numero ** 3

print(f"Numero -> {numero}")
print(f"Quadrado deste numero -> {quadrado}")
print(f"Cubo deste numero -> {cubo}")

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))

soma = num1 + num2

print(f"Os numeros {num1} e {num2} somados correspondem a {soma}")

num1 = float(input("Digite o primeiro número real: "))
num2 = float(input("Digite o segundo número real: "))

produto = num1 * num2

print(f"O produto dos numeros {num1} e {num2} corresponde a {produto}")

num1 = float(input("Digite o primeiro número real: "))
num2 = float(input("Digite o segundo número real: "))

soma = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2

print(f"Soma: {num1} + {num2} = {soma}")
print(f"Subtração: {num1} - {num2} = {subtracao}")
print(f"Multiplicação: {num1} * {num2} = {multiplicacao}")
print(f"Divisão: {num1} / {num2} = {divisao}")

