# -*- coding: utf-8 -*-
"""Lista 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9B5BC02hpe24UEm9taBoGXdO7c-DmlK

Nome: Arthur Pereira Vale

 Turma : Quinta N2

 Disciplina : Técnicas de desenvolvimento de algoritmo
"""

for i in range(10):
    print("Hello World!", end=" ")

for i in range(10):
    print("Hello World!")

for i in range(1, 101):
    print(i)

for i in range(1, 101):
    print(f"{i}- Hello World!")

for i in range(100, -1, -1):
    print(i)

for i in range(2, 1001, 2):
    print(i)

for i in range(999, -1, -2):
    print(i)

soma = 0
for i in range(1, 101):
    soma += i
print("Soma =", soma)

n = int(input("Quantas vezes imprimir Hello World? "))
for i in range(n):
    print("Hello World!")

palavra = input("Digite uma palavra: ")
n = int(input("Quantas vezes imprimir? "))
for i in range(n):
    print(palavra)

n = int(input("Quantos números deseja informar? "))
soma = 0
for i in range(n):
    x = float(input("Número: "))
    soma += x
print("Soma =", soma)
print("Média =", soma / n)

n = int(input("Quantas pessoas? "))
mais_velho_nome = ""
mais_velho_idade = -1
for i in range(n):
    nome = input("Nome: ")
    idade = int(input("Idade: "))
    if idade > mais_velho_idade:
        mais_velho_idade = idade
        mais_velho_nome = nome
print("Mais velho:", mais_velho_nome)

n = int(input("Quantas pessoas? "))
soma_m = soma_f = cont_m = cont_f = 0
for i in range(n):
    sexo = input("Sexo (M/F): ").upper()
    idade = int(input("Idade: "))
    if sexo == "M":
        soma_m += idade
        cont_m += 1
    elif sexo == "F":
        soma_f += idade
        cont_f += 1
print("Média idade Masculino:", soma_m / cont_m if cont_m > 0 else 0)
print("Média idade Feminino:", soma_f / cont_f if cont_f > 0 else 0)

numeros = []
for i in range(10):
    x = float(input("Número: "))
    numeros.append(x)
print("Maior =", max(numeros))
print("Menor =", min(numeros))

numeros = []
while True:
    x = float(input("Número (0 para parar): "))
    if x == 0:
        break
    numeros.append(x)
numeros.sort()
print("Ordenados:", numeros)

idades = []
while True:
    idade = int(input("Idade: "))
    idades.append(idade)
    cont = input("Deseja informar a próxima idade? (s/n): ").lower()
    if cont != "s":
        break

mais_novo = min(idades)
mais_velho = max(idades)
maiores18 = sum(1 for i in idades if i > 18)
ate18 = sum(1 for i in idades if i <= 18)
media = sum(idades) / len(idades)
idades.sort()
n = len(idades)
if n % 2 == 0:
    mediana = (idades[n//2 - 1] + idades[n//2]) / 2
else:
    mediana = idades[n//2]

print("Mais novo:", mais_novo)
print("Mais velho:", mais_velho)
print("Maiores de 18:", maiores18)
print("Até 18:", ate18)
print("Média:", media)
print("Mediana:", mediana)