# -*- coding: utf-8 -*-
"""lista 02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dCYMmgx2eBqW8Spr-M-_xZyUnp8wPTG

Nome: Arthur Pereira Vale

 Turma : Quinta N2

 Disciplina : Técnicas de desenvolvimento de algoritmo
"""

numero = float(input("Digite um número real: "))

if numero > 10:
    print(f"O número {numero} é maior que 10.")
else:
    print(f"O número {numero} não é maior que 10.")

numero = float(input("Digite um número real: "))

if numero >= 10:
    print(f"O número {numero} é maior ou igual a dez.")
else:
    print(f"O número {numero} é menor que dez.")

numero = float(input("Digite um número real: "))

if numero > 10:
    print(f"O número {numero} é maior que dez.")
elif numero < 10:
    print(f"O número {numero} é menor que dez.")
else:
    print(f"O número {numero} é igual a dez.")

numero = float(input("Digite um número real: "))

if numero > 0:
    print(f"O número {numero} é positivo.")
elif numero < 0:
    print(f"O número {numero} é negativo.")
else:
    print(f"O número {numero} é nulo (zero).")

numero = int(input("Digite um número inteiro: "))

if numero % 3 == 0:
    print(f"O número {numero} é múltiplo de 3.")
else:
    print(f"O número {numero} não é múltiplo de 3.")

numero = int(input("Digite o número a ser testado: "))
divisor = int(input("Digite o múltiplo (divisor) a ser testado: "))


if divisor == 0:
    print("O divisor não pode ser zero.")
elif numero % divisor == 0:
    print(f"O número {numero} é múltiplo de {divisor}.")
else:
    print(f"O número {numero} não é múltiplo de {divisor}.")

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
    print(f"O número {numero} é par.")
else:
    print(f"O número {numero} é ímpar.")

numero = float(input("Digite um número real: "))

if numero > 20:
    resultado = numero / 2
    print(f"O número {numero} é maior que 20. A metade é: {resultado}")
else:
    resultado = numero * 2
    print(f"O número {numero} não é maior que 20. O dobro é: {resultado}")

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))

soma = num1 + num2

if soma > 10:
    resultado = soma ** 2
    print(f"A soma ({soma}) é maior que 10. O quadrado da soma é: {resultado}")
else:
    resultado = soma / 2
    print(f"A soma ({soma}) não é maior que 10. A metade da soma é: {resultado}")

nota1 = float(input("Digite a nota da Prova 1 (peso 2): "))
nota2 = float(input("Digite a nota da Prova 2 (peso 3): "))
nota3 = float(input("Digite a nota da Prova 3 (peso 5): "))

soma_pesos = 2 + 3 + 5
media_final = ((nota1 * 2) + (nota2 * 3) + (nota3 * 5)) / soma_pesos

print(f"\nMédia Final: {media_final:.2f}")


if media_final >= 6.0:
    print("O aluno foi APROVADO.")
else:
    print("O aluno foi REPROVADO.")

nome1 = input("Nome da Pessoa 1: ")
peso1 = float(input(f"Peso de {nome1} (kg): "))
nome2 = input("Nome da Pessoa 2: ")
peso2 = float(input(f"Peso de {nome2} (kg): "))

if peso1 > peso2:
    print(f"A pessoa mais pesada é: {nome1}")
elif peso2 > peso1:
    print(f"A pessoa mais pesada é: {nome2}")
else:
    print("As duas pessoas têm o mesmo peso.")

numero = float(input("Digite um número: "))

if numero > 20 and numero < 90:
    print(f"O número {numero} está compreendido entre 20 e 90 (exclusivo).")
else:
    print(f"O número {numero} NÃO está compreendido entre 20 e 90.")

numA = float(input("Digite o primeiro número: "))
numB = float(input("Digite o segundo número: "))

if numA > numB:
    print(f"O primeiro número ({numA}) é maior e o segundo ({numB}) é menor.")
elif numB > numA:
    print(f"O segundo número ({numB}) é maior e o primeiro ({numA}) é menor.")
else:
    print("Os dois números são iguais.")

media_aprovacao = float(input("Digite a média mínima para aprovação: "))
nome = input("Digite o nome do(a) aluno(a): ")
sexo = input("Digite o sexo do(a) aluno(a) (M/F): ").upper()
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))

media_aluno = (nota1 + nota2 + nota3) / 3

if media_aluno >= media_aprovacao:
    status = "APROVADO(A)"
else:
    status = "REPROVADO(A)"

if sexo == 'F':
    artigo = "A aluna"
elif sexo == 'M':
    artigo = "O aluno"
else:
    artigo = "O(A) aluno(a)"

print("\n--- Resultado ---")
print(f"{artigo} {nome} foi {status} com média {media_aluno:.2f}")
print(f'Frase final: "O aluno {nome} foi {status} com média {media_aluno:.2f}"')

