# -*- coding: utf-8 -*-
"""2_notebook_Aplicacoes_ListaTuplasDicionarios_ProgramacaoPython_ADS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vf01EKBXYVRbc1FSbwfpYPMd3fMR-Dss

Nome: Arthur Pereira Vale

 Turma : Quinta N2

 Disciplina : Técnicas de desenvolvimento de algoritmo

# Lista, Tuplas e Dicionarios
"""

# MINI PROJETO 1: Cadastro Simplificado de Alunos (Lista de Dicionários)
# Objetivo: Gerenciar informações de alunos, simulando operações CRUD (Criar, Ler, Atualizar, Excluir).
# [cite_start]Estrutura: Lista (alunos_db) de Dicionários (cada aluno). [cite: 348, 344]

# Base de dados inicial (Lista de Dicionários)
alunos_db = [
    {"matricula": "2023001", "nome": "Ana Silva", "curso": "Sistemas de Informação"},
    {"matricula": "2023002", "nome": "João Gomes", "curso": "Engenharia de Software"},
    {"matricula": "2023003", "nome": "Maria Souza", "curso": "Ciência de Dados"}
]

print("1. Sistema Simplificado de Cadastro de Alunos")
print("-" * 40)

# 1. Adicionar Novo Aluno (CREATE)
print("- Adicionando novo aluno...")
novo_aluno = {"matricula": "2023004", "nome": "Pedro Costa", "curso": "Redes de Computadores"}
alunos_db.append(novo_aluno)
print(f"Aluno {novo_aluno['nome']} adicionado com sucesso.")

# 2. Buscar Aluno por Matrícula (READ)
matricula_busca = "2023002"
# [cite_start]Uso de compreensão de lista para buscar o dicionário do aluno pelo valor da chave 'matricula'. [cite: 371]
aluno_encontrado = next((aluno for aluno in alunos_db if aluno["matricula"] == matricula_busca), None)

if aluno_encontrado:
    print(f"\nAluno encontrado (Matrícula: {matricula_busca}):")
    # [cite_start]Acessa os valores do dicionário usando suas chaves. [cite: 377]
    print(f"Nome: {aluno_encontrado['nome']}, Curso: {aluno_encontrado['curso']}")
else:
    print(f"\nAluno com matrícula {matricula_busca} não encontrado.")

# 3. Atualizar Informação do Curso (UPDATE)
matricula_update = "2023003"
for aluno in alunos_db:
    if aluno["matricula"] == matricula_update:
        # [cite_start]Dicionários são mutáveis, permite alterar o valor da chave 'curso'. [cite: 391]
        aluno["curso"] = "Segurança da Informação"
        print(f"\nCurso do aluno {aluno['nome']} atualizado para: {aluno['curso']}")
        break

print("-" * 40)
# Visualiza a lista completa após as operações
print(alunos_db)

# MINI PROJETO 2: Gerenciamento de Coordenadas (Lista de Tuplas)
# [cite_start]Objetivo: Armazenar sequências de valores Fixos (latitude, longitude, nome). [cite: 409]
# [cite_start]Estrutura: Lista (locais) de Tuplas (cada coordenada), onde cada Tupla é imutável. [cite: 412, 414]

# Base de dados inicial (Lista de Tuplas: (latitude, longitude, nome_do_local))
locais = [
    (-23.55052, -46.63330, "São Paulo"),
    (-15.7801, -47.9292, "Brasília"),
    (40.7128, -74.0060, "Nova York")
]

print("\n2. Gerenciamento de Coordenadas Geográficas")
print("-" * 40)

# 1. Adicionar Nova Coordenada
print("-> Adicionando nova coordenada (Tupla)...")
# [cite_start]Cria uma nova tupla para garantir que a coordenada seja registrada de forma imutável. [cite: 433]
novo_local = (34.0522, -118.2437, "Los Angeles")
# [cite_start]A lista é mutável, permitindo adicionar a nova tupla. [cite: 435]
locais.append(novo_local)
print(f"Local {novo_local[2]} adicionado.")

# 2. Acessar e Desempacotar (Unpack) uma Tupla
print("\n-> Desempacotando a última coordenada...")
# [cite_start]Desempacota os elementos da última tupla da lista em variáveis separadas. [cite: 441]
lat, lon, nome = locais[-1]
print(f"Latitude: {lat}, Longitude: {lon}, Local: {nome}")

# 3. Iterar e Formatar Coordenadas
print("\n-> Coordenadas registradas:")
for coordenada in locais:
    # Acessa os elementos da tupla usando índices.
    print(f"Local: {coordenada[2]} | Lat/Lon: ({coordenada[0]}, {coordenada[1]})")

# [cite_start]Importante: Tuplas são imutáveis; tentar alterar um elemento resultaria em um erro. [cite: 456]
print("-" * 40)

# MINI PROJETO 3: Catálogo de Produtos com Busca Rápida (Dicionário)
# [cite_start]Objetivo: Mapear um ID de produto (chave) para os detalhes do produto (valor). [cite: 471]
# [cite_start]Estrutura: Dicionário (catalogo), onde a chave é o ID do produto, permitindo busca rápida. [cite: 475, 466]

# Catálogo de produtos (Dicionário aninhado)
catalogo = {
    "P001": {"nome": "Teclado Mecânico", "estoque": 25, "preco": 350.00},
    "P002": {"nome": "Monitor LED 27", "estoque": 18, "preco": 1200.00},
    "P003": {"nome": "Mouse Gamer", "estoque": 40, "preco": 150.00}
}

print("\n3. Catálogo de Produtos com Busca Rápida")
print("-" * 40)

# 1. Adicionar Novo Produto (CREATE)
novo_produto_id = "P004"
# [cite_start]Adiciona um novo par chave:valor. [cite: 494]
catalogo[novo_produto_id] = {"nome": "Webcam HD", "estoque": 50, "preco": 250.00}
print(f"Produto {catalogo[novo_produto_id]['nome']} adicionado ao catálogo.")

# 2. Buscar por Chave (Busca O(1) Rápida) (READ)
id_busca = "P002"
# [cite_start]Acessar diretamente pelo ID (chave) é a forma mais rápida de busca em um dicionário. [cite: 500]
if id_busca in catalogo:
    produto_detalhes = catalogo[id_busca]
    print(f"\nDetalhes do Produto {id_busca}:")
    print(f"Nome: {produto_detalhes['nome']}, Preço: R$ {produto_detalhes['preco']:.2f}")
else:
    print(f"\nProduto com ID {id_busca} não encontrado.")

# 3. Atualizar Estoque (UPDATE)
id_update = "P001"
# [cite_start]Acessa o dicionário interno pela chave e atualiza o valor. [cite: 514]
catalogo[id_update]["estoque"] = 5
print(f"\nEstoque do {catalogo[id_update]['nome']} atualizado. Novo estoque: {catalogo[id_update]['estoque']}")

print("-" * 40)

# MINI PROJETO 4: Agrupamento de Vendas por Região (Dicionários Aninhados e Tuplas)
# [cite_start]Objetivo: Agrupar dados de vendas (Lista de Tuplas) por uma chave de agrupamento (Região). [cite: 529]
# [cite_start]Estrutura: Dicionário (dados_vendas) onde a chave é a região e o valor contém uma Lista de Tuplas. [cite: 531, 532, 536]

# Dados de vendas (Dicionário Aninhado)
dados_vendas = {
    "SUDESTE": {
        "total_anual": 150000.00,
        # [cite_start]Lista de Tuplas: Cada tupla (imutável) é um registro de venda (id_venda, valor) [cite: 536]
        "vendas_detalhe": [
            ("V001", 5000.00),
            ("V002", 12000.00),
            ("V003", 8000.00)
        ]
    },
    "SUL": {
        "total_anual": 95000.00,
        "vendas_detalhe": [
            ("V004", 5500.00),
            ("V005", 10000.00)
        ]
    }
}

print("\n4. Agrupamento de Vendas por Região")
print("-" * 40)

# 1. Adicionar Nova Venda à Região SUDESTE
regiao = "SUDESTE"
nova_venda = ("V006", 9500.00)

# [cite_start]Acessa o dicionário 'SUDESTE', depois a chave 'vendas_detalhe' (que é uma lista), e adiciona a nova tupla. [cite: 573]
dados_vendas[regiao]["vendas_detalhe"].append(nova_venda)
print(f"Nova venda {nova_venda[0]} adicionada na região {regiao}.")

# 2. Calcular o Valor Total de Vendas Detalhadas no SUDESTE
vendas_sudeste = dados_vendas["SUDESTE"]["vendas_detalhe"]
# [cite_start]Usa compreensão de lista e a função sum() para somar o segundo elemento (valor) de cada tupla. [cite: 579]
soma_detalhes = sum(venda[1] for venda in vendas_sudeste)

print(f"\nSoma dos detalhes de vendas SUDESTE: R$ {soma_detalhes:.2f}")
print(f"Total anual registrado: R$ {dados_vendas[regiao]['total_anual']:.2f}")

# 3. Listar as Regiões (Chaves)
print("\nRegiões em análise:")
# [cite_start]O método .keys() retorna as chaves do dicionário principal. [cite: 588, 589]
for reg in dados_vendas.keys():
    print(f"- {reg}")

print("-" * 40)

# MINI PROJETO 5: Mapeamento de Níveis de Acesso (Dicionário com Tuplas)
# [cite_start]Objetivo: Definir conjuntos de permissões fixas por nível de usuário. [cite: 606]
# [cite_start]Estrutura: Dicionário (permissoes) mapeia o nível de acesso (chave) para uma Tupla imutável de permissões (valor). [cite: 601, 608, 609]

# Mapeamento de Níveis e Permissões
permissoes = {
    # [cite_start]Tupla de permissões para Admin [cite: 622]
    "ADMIN": ("CREATE_USER", "READ_ALL", "UPDATE_ANY", "DELETE_ALL"),
    # [cite_start]Tupla de permissões para Manager [cite: 623]
    "MANAGER": ("READ_ALL", "UPDATE_OWN"),
    # [cite_start]Tupla de um elemento para Viewer (vírgula obrigatória) [cite: 624]
    "VIEWER": ("READ_ALL",)
}

print("\n5. Mapeamento de Níveis de Acesso e Permissões")
print("-" * 40)

# 1. Acessar Permissões de um Nível Específico (READ)
nivel_acesso = "ADMIN"
# [cite_start]Acessa a tupla de permissões usando a chave do dicionário. [cite: 628]
perms_admin = permissoes.get(nivel_acesso)

if perms_admin:
    print(f"Permissões do nível {nivel_acesso}:")
    # [cite_start]Itera sobre a tupla de permissões. [cite: 634]
    for perm in perms_admin:
        print(f"- {perm}")
else:
    print(f"Nível de acesso '{nivel_acesso}' não definido.")

# 2. Verificar uma Permissão Específica
perm_verificar = "DELETE_ALL"
# [cite_start]Usa o operador 'in' para checar se a permissão existe dentro da tupla. [cite: 646]
if perm_verificar in permissoes["ADMIN"]:
    print(f"\nADMIN possui a permissão: {perm_verificar}")
else:
    print(f"\nADMIN NÃO possui a permissão: {perm_verificar}")

# 3. Tentativa de Adicionar uma Permissão (Imutabilidade da Tupla)
# print("Tentando adicionar permissão ao VIEWER...")
# [cite_start]permissoes["VIEWER"].append("DELETE_OWN") # Erro: 'tuple' object has no attribute 'append' [cite: 656]
# [cite_start]A tupla garante a integridade do conjunto de permissões. [cite: 657]
print("\nA Integridade do conjunto de permissões é garantida pela Tupla (Imutabilidade).")
print("-" * 40)