# -*- coding: utf-8 -*-
"""3_notebook_mini_projetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Apwf1EAKOw_ihBBqGEe12iAOKCZ9nZqV

Nome: Arthur Pereira Vale

 Turma : Quinta N2

 Disciplina : Técnicas de desenvolvimento de algoritmo
"""

# =====================================
# 2.1 Catálogo de Produtos
# =====================================

catalogo = [
    ("Smartphone", 1500, "Eletrônicos"),
    ("Tênis", 259, "Moda"),
    ("Notebook", 3500, "Eletrônicos"),
    ("Livro", 48, "Educação"),
    ("Fone de ouvido", 209, "Eletrônicos")
]

eletronicos = [produto for produto in catalogo if produto[2] == "Eletrônicos"]
assert len(eletronicos) == 3
print("Produtos eletrônicos:", eletronicos)

# =====================================
# 2.2 Carrinho de Compras
# =====================================

carrinho = {}
carrinho["Notebook"] = 1
carrinho["Fone de ouvido"] = 2
del carrinho["Notebook"]

assert "Notebook" not in carrinho
assert carrinho["Fone de ouvido"] == 2
print("Carrinho:", carrinho)

# =====================================
# 2.3 Cálculo de Total com Desconto
# =====================================

precos = [1500, 200, 3500]
precos_com_desconto = [p * 0.9 for p in precos]
total = sum(precos_com_desconto)

assert round(total, 2) == round(1500*0.9 + 200*0.9 + 3500*0.9, 2)
print(f"Total com desconto: R$ {total:.2f}")

# =====================================
# 2.4 Estoque por Categoria
# =====================================

estoque = {
    "Eletrônicos": ["Smartphone", "Notebook", "Fone de ouvido"],
    "Moda": ["Tênis", "Camisa"],
    "Educação": ["Livro"]
}

categoria_maior = max(estoque, key=lambda c: len(estoque[c]))
assert categoria_maior == "Eletrônicos"
print("Categoria com mais produtos:", categoria_maior)

# =====================================
# 3.1 Ranking de Jogadores
# =====================================

ranking = [("Ana", 120), ("Bruno", 280), ("Carlos", 180)]
ranking.sort(key=lambda x: x[1], reverse=True)

assert ranking[0][0] == "Bruno"
print("Top 3 jogadores:", ranking[:3])

# =====================================
# 3.2 Inventário de Itens
# =====================================

inventario = {
    "Espada": (1, "raro"),
    "Poção": (5, "comum"),
    "Armadura": (2, "épico")
}

raros = [item for item, (_, raridade) in inventario.items() if raridade in ["raro", "épico"]]
assert "Espada" in raros and "Armadura" in raros
print("Itens raros:", raros)

# =====================================
# 3.3 Histórico de Partidas
# =====================================

partidas = [
    ("Ana", "Bruno", "Ana"),
    ("Carlos", "Ana", "Carlos"),
    ("Bruno", "Carlos", "Carlos")
]

vitorias = {}
for _, _, vencedor in partidas:
    vitorias[vencedor] = vitorias.get(vencedor, 0) + 1

assert vitorias["Carlos"] == 2
print("Vitórias:", vitorias)

# =====================================
# 3.4 Configurações do Jogo
# =====================================

config = {
    "volume": 70,
    "dificuldade": "médio",
    "idioma": "português"
}

config["volume"] = 50
config["idioma"] = "inglês"

assert config["volume"] == 50
print("Configurações:", config)

# =====================================
# 4.1 Playlist de Músicas
# =====================================

playlist = [
    {"nome": "Música A", "artista": "Artista 1", "duracao": 2.5},
    {"nome": "Música B", "artista": "Artista 2", "duracao": 3.2},
    {"nome": "Música C", "artista": "Artista 1", "duracao": 4.0}
]

longas = [m["nome"] for m in playlist if m["duracao"] > 3]
assert "Música B" in longas and "Música C" in longas
print("Músicas com mais de 3 minutos:", longas)

# =====================================
# 4.2 Favoritar Músicas
# =====================================

favoritas = {
    "Música A": False,
    "Música B": True,
    "Música C": True
}

favoritas_listadas = [nome for nome, fav in favoritas.items() if fav]
assert len(favoritas_listadas) == 2
print("Favoritas:", favoritas_listadas)

# =====================================
# 4.3 Estatísticas da Playlist
# =====================================

musicas = [("Música A", 2.5), ("Música B", 3.2), ("Música C", 4.0)]
total = sum([dur for _, dur in musicas])
media = total / len(musicas)

assert round(media, 2) == round(total / 3, 2)
print(f"Total: {total:.2f} min | Média: {media:.2f} min")

# =====================================
# 4.4 Organizar por Artista
# =====================================

por_artista = {
    "Artista 1": ["Música A", "Música C"],
    "Artista 2": ["Música B"]
}

artista_top = max(por_artista, key=lambda a: len(por_artista[a]))
assert artista_top == "Artista 1"
print("Artista com mais músicas:", artista_top)